Reading from cli's push manifest
vinaypuppal/preact-cli-plugin-netlify pull request #14
Opened 2019-09-11 22:11 UTC by prateekbh

This changes from constructing the preload manifest ourselves to deferring it to what CLI generates.

**Diff**
Before:
```
/*
	Cache-Control: public, max-age=3600, no-cache
	Access-Control-Max-Age: 600
/sw.js
	Cache-Control: private, no-cache
/*.chunk.*.js
	Cache-Control: public, max-age=31536000
/blog.chunk.443ff.css
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-blog.chunk.443ff.css>; rel=preload; as=script
/blog.chunk.ebdc3.esm.js
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-blog.chunk.ebdc3.esm.js>; rel=preload; as=script
/.chunk.26439.css
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-home.chunk.26439.css>; rel=preload; as=script
/.chunk.9296d.esm.js
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-home.chunk.9296d.esm.js>; rel=preload; as=script
/photographs.chunk.96904.css
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-photographs.chunk.96904.css>; rel=preload; as=script
/photographs.chunk.7c15c.esm.js
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-photographs.chunk.7c15c.esm.js>; rel=preload; as=script
/blog
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-blog.chunk.a031c.js>; rel=preload; as=script
/
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-home.chunk.dd9f0.js>; rel=preload; as=script
/photographs
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script; crossorigin=anonymous
	Link: </route-photographs.chunk.ffd95.js>; rel=preload; as=script
```

After: 
```
/*
	Cache-Control: public, max-age=3600, no-cache
	Access-Control-Max-Age: 600
/sw.js
	Cache-Control: private, no-cache
/*.chunk.*.js
	Cache-Control: public, max-age=31536000
/
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script
	Link: </route-home.chunk.9296d.esm.js>; rel=preload; as=script
	Link: </route-home.chunk.26439.css>; rel=preload; as=style
/blog
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script
	Link: </route-blog.chunk.ebdc3.esm.js>; rel=preload; as=script
	Link: </route-blog.chunk.443ff.css>; rel=preload; as=style
/photographs
	Link: </bundle.4ab52.css>; rel=preload; as=style
	Link: </bundle.fd4ad.esm.js>; rel=preload; as=script
	Link: </route-photographs.chunk.7c15c.esm.js>; rel=preload; as=script
	Link: </route-photographs.chunk.96904.css>; rel=preload; as=style
```

No errornous preloads to every javascript/css file and correct preloads to the links

2019-09-12 16:36 UTC, vinaypuppal requested changes
Thanks, @prateekbh
Few questions
1. Seems like this code is not required now so can we remove it? https://github.com/vinaypuppal/preact-cli-plugin-netlify/blob/4203ab138d1eeb2c521384fc6ea89e222d1b72a1/index.js#L33-L45 
2. Below you can find a query related to ESM bundles

2019-09-12 16:36 UTC, vinaypuppal commented on index.js
> +          routePreloadText += `\n\tLink: </${file}>; rel=preload; as=${details.type}`
ESM preload links need to have `crossorigin=anonymous` as per the previous implementation so we need to support it here I think?

https://github.com/vinaypuppal/preact-cli-plugin-netlify/blob/4203ab138d1eeb2c521384fc6ea89e222d1b72a1/index.js#L38-L40

2019-09-15 04:23 UTC, prateekbh commented on index.js
> +          routePreloadText += `\n\tLink: </${file}>; rel=preload; as=${details.type}`
done

2019-09-15 04:23 UTC, prateekbh commented
addressed comments

2019-09-16 06:22 UTC, vinaypuppal approved these changes

2019-09-16 06:22 UTC, merged

2019-09-16 06:56 UTC, vinaypuppal commented
Thanks @prateekbh 
Published new version `v1.5.0` with these changes