adding capability to mutateManifest and order the preloads
vinaypuppal/preact-cli-plugin-netlify pull request #16
Opened 2020-06-11 18:42 UTC by prateekbh

- Order the preloads as CSS -> JS -> everything else. This makes sure [LCP](https://web.dev/lcp/) is not blocked on waiting for JS to download
- Adds an options to `mutateManifest` before generating headers out of it.

`mutateManifest` is useful as preact-cli does not currently build manifest for dynamic route e.g. `/product/*` so a user can add this/ modify based on something existing using this function

2020-06-15 17:18 UTC, prateekbh commented
cc: @vinaypuppal 👋🏻

2020-06-16 20:18 UTC, vinaypuppal requested changes
Hi @prateekbh 
Sorry did not notice this PR.
Thanks for these changes and nice to know about LCP.
Just one question which I asked below.
Rest all looks good. Can you also mention about `mutateManifest` in Readme.

Edit:
Sorry I am mobile and clicked on requested changes with a comment on `mutateManifest` but deleted as I understood later there was no issue.

2020-06-16 20:18 UTC, vinaypuppal commented on index.js
> +  constructor({ redirects, brotli = false, mutateManifest } = {}) {
This is used as function below but defaulted to empty object?

2020-06-16 20:20 UTC, vinaypuppal approved these changes

2020-06-16 20:23 UTC, prateekbh commented
@vinaypuppal Sorry I don't see any question.
Is it the request to add it to `readme`?

2020-06-16 20:27 UTC, vinaypuppal commented
Sorry I am on mobile and clicked on requested changes with a comment on `mutateManifest` but deleted as I understood later there was no issue with it.

Yes please add it to readme and you can merge. Also I added you as collaborator on NPM

2020-06-16 20:52 UTC, merged